from .schemas import XFoil_WarmStartIn, XFoil_WarmStartOut, XFoil_ConvergenceFlag
from .geometry import XFoil_Geometry_Write
from .build import XFoil_Build_Cp
from .convergence import XFoil_Check_ConvergenceCp
from .io import XFoil_Parse_Cp, XFoil_Write_Stdout
from .convert import XFoil_Cp_To_Conservative_State

import subprocess

import logging
logger = logging.getLogger(__name__)

def XFoil_Runner(XFoil_In: XFoil_WarmStartIn) -> XFoil_WarmStartOut:
    """
    Builds, runs, and handles i/o of the warm start procedure handled in XFoil. 

    Args:
        XFoil_In (XFoil_WarmStartIn): The standard warm start input data agreement

    Returns:
        XFoil_WarmStartOut: The standard warm start output data agreement
    """
    # Writes the geometry given the airfoil tensor, if it doesn't exist
    if XFoil_In.airfoil.coords_path is None:
        coords_path = XFoil_Geometry_Write(
            coords_tensor=XFoil_In.airfoil.coords_tensor, 
            working_dir=XFoil_In.working_dir, 
            airfoil_name=XFoil_In.airfoil.airfoil_name
        )
        XFoil_In.airfoil.coords_path = coords_path

    # Builds the exact command sequence we will execute
    input_script_path, cp_file_path = XFoil_Build_Cp(
        coords_path=XFoil_In.airfoil.coords_path,
        working_dir=XFoil_In.working_dir,
        alpha=XFoil_In.freestream.alpha,
        Re=XFoil_In.freestream.Re,
        mach=XFoil_In.freestream.mach,
        n_panels=XFoil_In.solver_config.n_panels,
        max_iterations=XFoil_In.solver_config.max_iterations
    )

    # Runs the subprocess, gets flag and stdout
    flag, stdout = XFoil_Run_Cp(
        xfoil_exe=XFoil_In.xfoil_exe,
        input_script_path=input_script_path,
        cp_file_path=cp_file_path,
        timeout_sec=XFoil_In.solver_config.timeout_sec,
        tolerance=XFoil_In.conv_config.tolerance,
        tail_length=XFoil_In.conv_config.tail_length,
        var_thresh=XFoil_In.conv_config.var_thresh,
        slope_thresh=XFoil_In.conv_config.slope_thresh
    )

    Cp_tensor = None
    conservative_tensor = None
    if flag == XFoil_ConvergenceFlag.CONVERGED.value: # parse and convert iff it converged, if not, it is not useful for further analysis
        # Parses the written Cp.dat file, and converts it into proper conservative values
        Cp_tensor = XFoil_Parse_Cp(cp_file_path=cp_file_path)
        conservative_tensor = XFoil_Cp_To_Conservative_State(
            Cp_tensor=Cp_tensor,
            coords_tensor=XFoil_In.airfoil.coords_tensor,
            M_inf=XFoil_In.freestream.mach,
            altitude_m=XFoil_In.freestream.altitude_m,
            alpha=XFoil_In.freestream.alpha
        )

    # Write the stdout, build the verbose path list
    stdout_file_path = XFoil_Write_Stdout(working_dir=XFoil_In.working_dir, stdout=stdout)
    verbose_list = [input_script_path, cp_file_path, stdout_file_path]

    return XFoil_WarmStartOut(
        airfoil=XFoil_In.airfoil,
        freestream=XFoil_In.freestream,
        flag=flag,
        Cp_tensor=Cp_tensor,
        conservative_tensor=conservative_tensor,
        verbose_list=verbose_list
    )

def XFoil_Run_Cp(xfoil_exe: str, input_script_path: str, cp_file_path: str, timeout_sec: int, tolerance: float, tail_length: int, var_thresh: float, slope_thresh: float) -> tuple[int, str]:
    """
    Runs the given input script in XFoil, to compute the Cp distribtuion around the airfoil.

    Args:
        xfoil_exe (str): Path to the XFoil executable
        input_script_path (str): Path to the XFoil input script generated by the builder
        cp_file_path (str): Path to the Cp file to be outputted by XFoil
        timeout_sec (int): Maximum time to wait for XFoil to finish before terminating
        tolerance (float): The required accuracy
        tail_length (int): The window to be used when checking resids for convergence
        var_thresh (float): The threshold for the variance at tail for convergence
        slope_thresh (float): The threshold for the slope at tail for convergence
    
    Returns:
        int: The convergence flag of the XFoil run; for details, please refer to the ConvergenceFlag data agreement.
        str: The stdout of the ran XFoil subprocess.
    """

    with open(input_script_path, "r") as stdin_file:
        try:
            process = subprocess.run(
                [xfoil_exe],
                stdin=stdin_file,
                capture_output=True,
                timeout=timeout_sec,
                text=True
            )
            if process.returncode != 0:
                logger.error(f"XFoil execution failed with return code {process.returncode}. Stderr: {process.stderr}. Output: {process.stdout}")
                return XFoil_ConvergenceFlag.FAILED.value, process.stdout
            
            flag = XFoil_Check_ConvergenceCp(process.stdout, cp_file_path, tolerance, tail_length, var_thresh, slope_thresh)

            if flag == XFoil_ConvergenceFlag.FAILED.value:
                logger.warning(f"XFoil execution failed")

            elif flag == XFoil_ConvergenceFlag.DIVERGED.value:
                logger.warning(f"XFoil execution diverged")

            elif flag == XFoil_ConvergenceFlag.OSCILLATORY.value:
                logger.warning(f"XFoil execution oscillated")

            elif flag == XFoil_ConvergenceFlag.ITER_LIMITED.value:
                logger.warning(f"XFoil execution reached iteration limit without convergence")

            elif flag == XFoil_ConvergenceFlag.STAGNATED.value:
                logger.warning(f"XFoil execution stagnated")

            elif flag == XFoil_ConvergenceFlag.CONVERGED.value:
                logger.info(f"XFoil execution converged")

            else:
                logger.warning(f"Unknown/Unsupported convergence flag: {flag}")

            return flag, process.stdout
            
        except subprocess.TimeoutExpired:
            logger.error(f"XFoil execution timed out after {timeout_sec} seconds. Process will be terminated.")
            return XFoil_ConvergenceFlag.FAILED.value, "TIMEOUT"