from src.datagen.schemas import XFoil_WarmStartIn, XFoil_WarmStartOut, XFoilConvergenceFlag
from src.datagen.solvers.xfoil.convergence import XFoil_Check_ConvergenceCp

import subprocess

import logging
logger = logging.getLogger(__name__)

def XFoilRunner(X: XFoil_WarmStartIn) -> XFoil_WarmStartOut:
    pass

def XFoil_Run_Cp(xfoil_exe: str, input_script_path: str, cp_file_path: str, timeout_sec: int=60) -> tuple[int, str]:
    """
    Runs the given input script in XFoil, to compute the Cp distribtuion around the airfoil.

    Args:
        xfoil_exe (str): Path to the XFoil executable
        input_script_path (str): Path to the XFoil input script generated by the builder
        cp_file_path (str): Path to the Cp file to be outputted by XFoil
        timeout_sec (int, optional): Maximum time to wait for XFoil to finish before terminating. Defaults to 60 seconds.
    
    Returns:
        int: The convergence flag of the XFoil run; for details, please refer to the ConvergenceFlag data agreement.
        str: The stdout of the ran XFoil subprocess.
    """

    with open(input_script_path, "r") as stdin_file:
        try:
            process = subprocess.run(
                [xfoil_exe],
                stdin=stdin_file,
                capture_output=True,
                timeout=timeout_sec,
                text=True
            )
            if process.returncode != 0:
                logger.error(f"XFoil execution failed with return code {process.returncode}. Stderr: {process.stderr}. Output: {process.stdout}")
                return XFoilConvergenceFlag.FAILED.value, process.stdout
            
            flag = XFoil_Check_ConvergenceCp(process.stdout, cp_file_path)

            if flag == XFoilConvergenceFlag.FAILED.value:
                logger.warning(f"XFoil execution failed")

            elif flag == XFoilConvergenceFlag.DIVERGED.value:
                logger.warning(f"XFoil execution diverged")

            elif flag == XFoilConvergenceFlag.OSCILLATORY.value:
                logger.warning(f"XFoil execution oscillated")

            elif flag == XFoilConvergenceFlag.CONVERGED.value:
                pass

            else:
                logger.warning(f"Unknown/Unsupported convergence flag: {flag}")

            return flag, process.stdout
            
        except subprocess.TimeoutExpired:
            logger.error(f"XFoil execution timed out after {timeout_sec} seconds. Process will be terminated.")
            return XFoilConvergenceFlag.FAILED.value, "TIMEOUT"